use std::{
    fmt::{Debug, Display},
    hash::Hash,
};

use serde::{Serialize, de::DeserializeOwned};
use sqlx::{Encode, FromRow, Postgres, Type, postgres::PgRow};
use uuid::Uuid;

pub mod cached;
pub mod error;
pub mod expr;
pub mod unbinded_query;
pub mod value;

pub use unbinded_query::UnbindedQuery;
pub use unbinded_query::push_conditions;

use crate::shared::value::SqlParam;

/// Conflict resolution strategy for `INSERT ... ON CONFLICT`.
pub enum SqlConflict<C: AsRef<str>> {
    /// `ON CONFLICT DO NOTHING` — silently skip conflicting rows.
    DoNothing,
    /// `ON CONFLICT (conflict_cols) DO UPDATE SET update_cols = EXCLUDED.update_cols`.
    DoUpdate { conflict_cols: Vec<C>, update_cols: Vec<C> },
    /// `ON CONFLICT ON CONSTRAINT name DO UPDATE SET ...` — target a named constraint.
    OnConstraint { name: &'static str, update_cols: Vec<C> },
}

/// Implemented by column enums that have a primary-key variant.
/// Generated automatically by `#[derive(SqlCols)]` when the struct has an `id` field.
pub trait SqlColId {
    /// Returns the column enum variant representing the primary key.
    fn id() -> Self;
}

pub struct Cte {
    pub name: String,
    pub sql: String,
    pub binds: Vec<SqlParam>,
    pub tables: Vec<&'static str>,
}

pub fn prepend_ctes(
    ctes: Vec<Cte>,
    sql: &mut String,
    binds: &mut Vec<SqlParam>,
    tables: &mut Vec<&'static str>,
) {
    if ctes.is_empty() {
        return;
    }
    let mut prefix = String::from("WITH ");
    let mut cte_binds = vec![];
    for (i, cte) in ctes.into_iter().enumerate() {
        if i > 0 {
            prefix.push_str(", ");
        }
        prefix.push_str(&cte.name);
        prefix.push_str(" AS (");
        prefix.push_str(&cte.sql);
        prefix.push(')');
        cte_binds.extend(cte.binds);
        for t in cte.tables {
            if !tables.contains(&t) {
                tables.push(t);
            }
        }
    }
    prefix.push(' ');
    prefix.push_str(sql);
    *sql = prefix;
    cte_binds.append(binds);
    *binds = cte_binds;
}

pub enum Returning {
    None,
    All,
    Columns(Vec<String>),
}

pub fn push_returning(returning: Returning, sql: &mut String) {
    match returning {
        Returning::None => {}
        Returning::All => {
            sql.push_str(" RETURNING *");
        }
        Returning::Columns(cols) => {
            sql.push_str(" RETURNING ");
            for (i, col) in cols.iter().enumerate() {
                if i > 0 {
                    sql.push_str(", ");
                }
                sql.push_str(col);
            }
        }
    }
}

/// Maps a Rust struct to a Postgres table.
///
/// Typically the struct derives `FromRow` + `SqlCols`, and this trait is
/// implemented manually to wire everything together:
///
/// ```ignore
/// impl Table for Users {
///     type Col = UsersCol;       // generated by #[derive(SqlCols)]
///     type Id = UserId;          // generated by define_id!()
///     const TABLE_NAME: &'static str = "users";
///     const PRIMARY_KEY: &'static str = "id";
/// }
/// ```
pub trait Table: for<'r> FromRow<'r, PgRow> + Send + Unpin + Debug + 'static {
    /// The column enum generated by `#[derive(SqlCols)]`.
    type Col: AsRef<str> + Display + Copy + expr::ColOps<Self>;
    /// The primary-key newtype generated by `define_id!()`.
    type Id: Id + Into<SqlParam>;
    /// The Postgres table name, used in `FROM`, `INSERT INTO`, etc.
    const TABLE_NAME: &'static str;
    /// The primary-key column name, used by `select_one_id` / `delete_one_id`.
    const PRIMARY_KEY: &'static str;
}

/// Trait shared by all newtype ID wrappers.
///
/// Provides conversion to/from the raw `Uuid` and bounds required by
/// handlers, services, and the query layer.
pub trait Id:
    Copy
    + Clone
    + Debug
    + Display
    + PartialEq
    + Eq
    + Hash
    + Serialize
    + DeserializeOwned
    + Send
    + Sync
    + for<'q> Encode<'q, Postgres>
    + Type<Postgres>
    + 'static
{
    fn new() -> Self;
    fn from_raw(id: Uuid) -> Self;
    fn raw(self) -> Uuid;
}

/// Generate a newtype ID wrapper with all required trait implementations.
///
/// ```ignore
/// define_id!(AccountId);
/// ```
#[macro_export]
macro_rules! define_id {
    ($name:ident) => {
        #[derive(
            Copy,
            Clone,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::serde::Serialize,
            ::serde::Deserialize,
            ::sqlx::Type,
        )]
        #[serde(transparent)]
        #[sqlx(transparent)]
        pub struct $name(pub ::uuid::Uuid);

        impl $crate::Id for $name {
            #[inline]
            fn new() -> Self {
                Self(::uuid::Uuid::now_v7())
            }

            #[inline]
            fn from_raw(id: ::uuid::Uuid) -> Self {
                Self(id)
            }

            #[inline]
            fn raw(self) -> ::uuid::Uuid {
                self.0
            }
        }

        impl ::std::default::Default for $name {
            #[inline]
            fn default() -> Self {
                Self(::uuid::Uuid::nil())
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }

        impl ::std::str::FromStr for $name {
            type Err = ::uuid::Error;
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                s.parse::<::uuid::Uuid>().map(Self)
            }
        }

        impl From<::uuid::Uuid> for $name {
            #[inline]
            fn from(id: ::uuid::Uuid) -> Self {
                Self(id)
            }
        }

        impl From<$name> for ::uuid::Uuid {
            #[inline]
            fn from(id: $name) -> Self {
                id.0
            }
        }

        impl From<$name> for $crate::SqlParam {
            fn from(id: $name) -> Self {
                $crate::SqlParam::Uuid(id.0)
            }
        }

        impl ::ts_rs::TS for $name {
            type WithoutGenerics = Self;
            type OptionInnerType = Self;

            fn name(cfg: &::ts_rs::Config) -> String {
                <::uuid::Uuid as ::ts_rs::TS>::name(cfg)
            }

            fn inline(cfg: &::ts_rs::Config) -> String {
                <::uuid::Uuid as ::ts_rs::TS>::inline(cfg)
            }

            fn output_path() -> Option<std::path::PathBuf> {
                None
            }
        }
    };
}
